<a href="https://colab.research.google.com/github/2303A51097/B-02_PFDS_1097/blob/main/LAB_03_PFDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
#lab-03 question 1
import numpy as np
a1 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
a2 = np.array([[9, 8, 7],
               [6, 5, 4],
               [3, 2, 1]])
add_res = np.add(a1,a2)
sub_res = np.subtract(a1,a2)
print("Matrix 1:\n",a1)
print("Matrix 2:\n",a2)
print("Addition Result:\n",add_res)
print("Subtraction Result:\n",sub_res)

Matrix 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix 2:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Addition Result:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction Result:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [13]:
#lab-03 question 2
import numpy as np
m= np.array([[1, 2],
              [3, 4],
              [5, 6]])
n= np.array([[7, 8, 9],
              [10, 11, 12]])
dot_res = np.dot(m,n)
print("Matrix m:\n",m)
print("Matrix n:\n",n)
print("Dot Product Result:\n",dot_res)

Matrix m:
 [[1 2]
 [3 4]
 [5 6]]
Matrix n:
 [[ 7  8  9]
 [10 11 12]]
Dot Product Result:
 [[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


In [ ]:
#files
filename = "student_data.txt"
name=input("Enter name: ")
marks=input("Enter marks: ")
with open(filename, "a") as fp:
    fp.write(f"{name},{marks}\n")
print("\nAll Entries Of Students:")
with open(file_name, "r") as fp:
    for line in fp:
        n,m = line.strip().split(",")
        print(f"Name: {n}, Marks: {m}")